UPDATE posts SET title = '안드로이드 앱 개발 환경 준비 - Android Studio, JDK 17, SDK Manager 및 AVD 설정', seo_title = '안드로이드 개발 환경 구축 - Android Studio, SDK, AVD 에뮬레이터 & ADB 설정' WHERE id = 1079;
UPDATE posts SET title = '안드로이드 앱의 기본 구조 - AndroidManifest.xml, Gradle 빌드 스크립트 및 APK/AAB 생성', seo_title = '안드로이드 프로젝트 구조 - AndroidManifest.xml, Gradle(build.gradle.kts) & APK/AAB' WHERE id = 1080;
UPDATE posts SET title = '코틀린(Kotlin) 프로그래밍 기초 - 변수 val/var, 데이터 타입, 함수 및 Null Safety', seo_title = '코틀린 기초 문법 - val/var, 데이터 타입, when 제어문 & Null Safety(?., ?:, !!)' WHERE id = 1081;
UPDATE posts SET title = '코틀린 객체지향 프로그래밍(OOP) - 클래스, 생성자, 상속, 인터페이스 및 Data Class', seo_title = '코틀린 객체지향 OOP - 클래스, 주/부 생성자, 상속(open), 인터페이스, Data Class' WHERE id = 1082;
UPDATE posts SET title = '코틀린의 유용한 기법 - 람다 표현식, 고차 함수, 확장 함수 및 Scope Functions (let, apply, run)', seo_title = '코틀린 고급 기법 - 람다, 고차 함수, 확장 함수 & Scope Functions (let, run, apply, also)' WHERE id = 1083;
UPDATE posts SET title = '뷰(View)를 이용한 화면 구성 - View 계층 구조, TextView, EditText, Button 및 ImageView', seo_title = '안드로이드 뷰 컴포넌트 - View, TextView, EditText, Button, ImageView & CheckBox' WHERE id = 1084;
UPDATE posts SET title = '뷰를 배치하는 레이아웃 - LinearLayout, RelativeLayout, FrameLayout 및 ConstraintLayout 제약 조건', seo_title = '안드로이드 레이아웃 - LinearLayout, RelativeLayout, FrameLayout & ConstraintLayout' WHERE id = 1085;
UPDATE posts SET title = '사용자 이벤트 처리하기 - 터치 이벤트, 키 이벤트 및 Event Listener 람다 패턴', seo_title = '안드로이드 이벤트 처리 - TouchEvent, KeyEvent & OnClickListener 람다 패턴' WHERE id = 1086;
UPDATE posts SET title = '리소스 활용하기 - res 디렉토리 (strings, colors, drawables) 및 화면 대응 수식어', seo_title = '안드로이드 리소스 - res 디렉토리, strings.xml, colors.xml, drawables & 다국어 지원' WHERE id = 1087;
UPDATE posts SET title = '다이얼로그와 알림 이용하기 - Toast, AlertDialog, Pickers 및 NotificationChannel', seo_title = '안드로이드 알림 - Toast, AlertDialog, DatePickerDialog & NotificationChannel' WHERE id = 1088;
UPDATE posts SET title = '제트팩 라이브러리 - ViewBinding, Fragment 생명주기, ViewPager2 및 RecyclerView', seo_title = '안드로이드 제트팩 - ViewBinding, Fragment 생명주기, ViewPager2 & RecyclerView' WHERE id = 1089;
UPDATE posts SET title = '머티리얼 라이브러리 - Material Design 3, Toolbar, DrawerLayout, BottomNavigationView', seo_title = '머티리얼 디자인 3 - AppbarLayout, MaterialToolbar, DrawerLayout & BottomNavigationView' WHERE id = 1090;
UPDATE posts SET title = '액티비티 컴포넌트 - Activity 생명주기(Lifecycle), Intent 및 Activity Result API', seo_title = '안드로이드 액티비티 - Activity 생명주기, 명시적/암시적 Intent & Activity Result API' WHERE id = 1091;
UPDATE posts SET title = '브로드캐스트리시버 컴포넌트 - 동적/정적 리시버 등록 및 시스템 브로드캐스트 이벤트', seo_title = '브로드캐스트 리시버 - 동적/정적 Receiver, 배터리/부팅/네트워크 시스템 이벤트' WHERE id = 1092;
UPDATE posts SET title = '서비스 컴포넌트 - Foreground Service, Bound Service 및 WorkManager 비동기 작업', seo_title = '안드로이드 서비스 - Foreground Service, Bound Service, Notification & WorkManager' WHERE id = 1093;
UPDATE posts SET title = '콘텐츠 프로바이더 컴포넌트 - Uri, ContentResolver 및 갤러리/주소록 외부 데이터 공유', seo_title = '콘텐츠 프로바이더 - ContentProvider, Uri, ContentResolver & Scoped Storage' WHERE id = 1094;
UPDATE posts SET title = '저장소에 데이터 보관하기 - DataStore 및 룸(Room) SQLite ORM 라이브러리', seo_title = '안드로이드 데이터 저장소 - SharedPreferences, DataStore & Room DB (Entity, DAO)' WHERE id = 1095;
UPDATE posts SET title = '네트워크 프로그래밍 - HTTP 통신, Retrofit2, OkHttp3 및 Coroutines 비동기 처리', seo_title = '안드로이드 네트워크 - Retrofit2, OkHttp3, JSON 파싱 & Kotlin Coroutines' WHERE id = 1096;
UPDATE posts SET title = '위치 정보 활용하기 - FusedLocationProviderClient, 위치 권한 및 Google Maps API', seo_title = '안드로이드 위치 정보 - FusedLocationProviderClient, GPS 권한 & Google Maps API' WHERE id = 1097;
UPDATE posts SET title = '파이어베이스 연동과 인증 기능 - Firebase SDK 설정 및 Firebase Authentication', seo_title = '파이어베이스 연동 - Firebase SDK, google-services.json & Firebase Auth 인증' WHERE id = 1098;
UPDATE posts SET title = '파이어스토어, 스토리지, FCM - Cloud Firestore NoSQL DB, Storage 및 푸시 알림 FCM', seo_title = '파이어베이스 실전 - Cloud Firestore NoSQL, Firebase Storage & FCM 푸시 알림' WHERE id = 1099;
UPDATE posts SET title = '알고리즘 성능 분석 기초 - 시간 복잡도, 공간 복잡도 및 Big-O 표기법', seo_title = '알고리즘 복잡도 분석 - 시간 복잡도, 공간 복잡도, Big-O / Big-Omega / Big-Theta' WHERE id = 1388;
UPDATE posts SET title = '재귀(Recursion)와 분할 정복(Divide and Conquer) - 콜 스택, 팩토리얼 및 마스터 정리', seo_title = '재귀 함수와 분할 정복 - Call Stack, 팩토리얼, 하노이의 탑 & 마스터 정리' WHERE id = 1389;
UPDATE posts SET title = '정렬 알고리즘 1: 비교 정렬 - 버블 정렬(Bubble), 선택 정렬(Selection) 및 삽입 정렬(Insertion)', seo_title = '기초 정렬 알고리즘 - 버블 정렬, 선택 정렬, 삽입 정렬 $O(N^2)$ 원리와 최적화' WHERE id = 1390;
UPDATE posts SET title = '정렬 알고리즘 2: 고속 정렬 - 퀵 정렬(Quick Sort), 병합 정렬(Merge Sort) 및 힙 정렬(Heap Sort)', seo_title = '고속 정렬 알고리즘 - 퀵 정렬, 병합 정렬, 힙 정렬 평균 $O(N \log N)$ 완벽 해설' WHERE id = 1391;
UPDATE posts SET title = '정렬 알고리즘 3: 비비교 정렬 및 정렬 안정성 - 계수 정렬, 기수 정렬 및 Stable Sort', seo_title = '비비교 정렬 & 안정성 - 계수 정렬(Counting Sort), 기수 정렬(Radix Sort) & Stable Sort' WHERE id = 1392;
UPDATE posts SET title = '이분 탐색(Binary Search)과 매개변수 탐색(Parametric Search) - Lower/Upper Bound', seo_title = '이분 탐색 & 매개변수 탐색 - Binary Search $O(\log N)$, Lower Bound, Upper Bound' WHERE id = 1393;
UPDATE posts SET title = '투 포인터(Two Pointers)와 슬라이딩 윈도우(Sliding Window) - 1차원 배열 $O(N)$ 연속 탐색', seo_title = '투 포인터 & 슬라이딩 윈도우 - Two Pointers, Sliding Window 1차원 배열 $O(N)$ 탐색' WHERE id = 1394;
UPDATE posts SET title = '탐욕법(Greedy Algorithm) - 그리디 선택 속성, 회의실 배정 및 분할 배낭 문제', seo_title = '그리디 알고리즘 - Greedy Algorithm, 탐욕적 선택 속성, 회의실 배정 & 분할 배낭' WHERE id = 1395;
UPDATE posts SET title = '동적 계획법(Dynamic Programming) 1: 기초 - Top-down(메모이제이션) vs Bottom-up(타뷸레이션)', seo_title = '동적 계획법 DP 1 - DP 개념, Top-down (Memoization) vs Bottom-up (Tabulation)' WHERE id = 1396;
UPDATE posts SET title = '동적 계획법(DP) 2: 실전 대표 문제 - LIS($O(N \log N)$), 0-1 배낭 문제 및 편집 거리', seo_title = '동적 계획법 DP 2 - LIS 최장 증가 부분 수열, 0-1 Knapsack 배낭 문제 & 편집 거리' WHERE id = 1397;
UPDATE posts SET title = '백트래킹(Backtracking)과 상태 공간 트리 - 가지치기(Pruning), N-Queen 문제 및 스도쿠', seo_title = '백트래킹 & 가지치기 - Backtracking, State Space Tree, Pruning & N-Queen 문제' WHERE id = 1398;
UPDATE posts SET title = '그래프 탐색 - 깊이 우선 탐색(DFS), 너비 우선 탐색(BFS) 및 미로 최단 거리', seo_title = '그래프 탐색 - DFS (Depth First Search), BFS (Breadth First Search) & 최단 경로' WHERE id = 1399;
UPDATE posts SET title = '단일 출발지 최단 경로 알고리즘 - 다익스트라(Dijkstra)와 벨만-포드(Bellman-Ford)', seo_title = '최단 경로 알고리즘 1 - 다익스트라(Dijkstra $O((E+V)\log V)$), 벨만-포드(Bellman-Ford)' WHERE id = 1400;
UPDATE posts SET title = '모든 쌍 최단 경로 알고리즘 - 플로이드-워셜(Floyd-Warshall $O(V^3)$)과 경유지 DP', seo_title = '최단 경로 알고리즘 2 - 플로이드-워셜(Floyd-Warshall $O(V^3)$) & 3중 루프 DP' WHERE id = 1401;
UPDATE posts SET title = '최소 신장 트리(MST) - 크루스칼(Kruskal: Union-Find)과 프림(Prim: Priority Queue)', seo_title = '최소 신장 트리 MST - 크루스칼(Kruskal), 프림(Prim) & 서로소 집합 Union-Find' WHERE id = 1402;
UPDATE posts SET title = '위상 정렬(Topological Sort)과 방향 비순환 그래프(DAG) - 진입 차수와 Kahn 알고리즘', seo_title = '위상 정렬 Topological Sort - DAG, 진입 차수(Indegree), Kahn 큐 알고리즘 & 사이클 검증' WHERE id = 1403;
UPDATE posts SET title = '문자열 검색 알고리즘 - KMP(Knuth-Morris-Pratt $O(N+M)$)와 라빈-카프(Rabin-Karp)', seo_title = '문자열 탐색 알고리즘 - KMP 알고리즘, 실패 함수(LPS 배열) & 라빈-카프 롤링 해시' WHERE id = 1404;
UPDATE posts SET title = '트리 심화 - 최소 공통 조상(LCA: Lowest Common Ancestor) 및 희소 배열(Sparse Table)', seo_title = '트리 LCA 알고리즘 - 최소 공통 조상(Lowest Common Ancestor), 희소 배열 $O(\log N)$' WHERE id = 1405;
UPDATE posts SET title = '구간 쿼리 자료구조 - 세그먼트 트리(Segment Tree) 및 느리게 갱신되는 세그먼트 트리', seo_title = '세그먼트 트리 - Segment Tree $O(\log N)$ 구간합 쿼리 & Lazy Propagation 느린 갱신' WHERE id = 1406;
UPDATE posts SET title = '비트마스킹(Bitmasking)과 외판원 순회 문제(TSP: Traveling Salesperson Problem)', seo_title = '비트마스킹 & TSP - Bitmask 연산자, 외판원 순회 문제 DP + Bitmask $O(N^2 2^N)$' WHERE id = 1407;
UPDATE posts SET title = 'Anthropic 공식 AI 코딩 어시스턴트 Claude Code 설치 및 실전 활용 완벽 가이드', seo_title = 'Claude Code 설치 가이드 - CLI AI 코딩 어시스턴트, IDE 연동, 트러블슈팅 및 명령어 총정리' WHERE id = 1408;
UPDATE posts SET title = 'AI 에이전트 성능을 10배 올리는 하네스 엔지니어링(Harness Engineering) 완벽 가이드', seo_title = '하네스 엔지니어링 완벽 가이드 - Agent = Model + Harness, AGENTS.md 및 4대 기둥' WHERE id = 1409;
UPDATE posts SET title = '하네스 엔지니어링 완전 정복 [1부: 원론과 4대 기둥 (Constrain · Inform · Verify · Correct)]', seo_title = '하네스 엔지니어링 완전 정복 1부 - Agent = Model + Harness 원론 및 4대 기둥' WHERE id = 1410;
UPDATE posts SET title = '하네스 엔지니어링 완전 정복 [2부: 실전 설계, 플랫폼 비교 & EDD]', seo_title = '하네스 엔지니어링 완전 정복 2부 - AGENTS.md 설계, 도구 패턴, 플랫폼 비교 및 EDD' WHERE id = 1411;
UPDATE posts SET title = '하네스 엔지니어링 완전 정복 [3부: 차세대 에이전트 오케스트레이션 & 130개 공식 소스 맵]', seo_title = '하네스 엔지니어링 3부 - 차세대 오케스트레이션, 용어집 및 130+ 공식 소스 맵' WHERE id = 1412;
UPDATE posts SET title = 'Codex 사용법 [1편: 에이전트 패러다임 전환과 작업 책임선]', seo_title = 'Codex 사용법 1편 - GPT-5 시대 실무형 AI 워커 패러다임 및 책임선' WHERE id = 1413;
UPDATE posts SET title = 'Codex 사용법 [2편: 프롬프트 계약, AGENTS.md 팀 헌법과 컨텍스트]', seo_title = 'Codex 사용법 2편 - 프롬프트 작업 계약, 창구 전환 및 AGENTS.md 팀 헌법' WHERE id = 1414;
UPDATE posts SET title = 'Codex 사용법 [3편: 문맥 엔지니어링, 자가 디버깅 & TDD]', seo_title = 'Codex 사용법 3편 - 문맥 엔지니어링, 최소 타격 버그 수정 및 TDD' WHERE id = 1415;
UPDATE posts SET title = 'Codex 사용법 [4편: 멀티모달 UI, Figma 연동 & Visual Verification]', seo_title = 'Codex 사용법 4편 - 스크린샷 변환, Visual Verification & Figma 동기화' WHERE id = 1416;
UPDATE posts SET title = 'Codex 사용법 [5편: ChatGPT App, SwiftUI & 브라우저 게임]', seo_title = 'Codex 사용법 5편 - ChatGPT 대화형 앱, SwiftUI iOS 앱 & 멀티모달 게임' WHERE id = 1417;
UPDATE posts SET title = 'Codex 사용법 [6편: API 마이그레이션, 데이터 분석 & 릴리즈]', seo_title = 'Codex 사용법 6편 - Zero-Downtime API 마이그레이션, 데이터 리포트 & 릴리즈' WHERE id = 1424;
UPDATE posts SET title = 'Codex 사용법 [7편: AI 코드 리뷰, CI/CD & 배포 파이프라인]', seo_title = 'Codex 사용법 7편 - GitHub Actions AI 코드 리뷰, codex exec & 배포 검증' WHERE id = 1425;
UPDATE posts SET title = 'Codex 사용법 [8편: MCP 확장, 스킬 굳히기 & Worktree 서브에이전트]', seo_title = 'Codex 사용법 8편 - skills/ 모듈화, MCP 3대 통합 & Git Worktree 서브에이전트' WHERE id = 1426;
UPDATE posts SET title = 'Codex 사용법 [9편: 보안, 권한, 인시던트 & 거버넌스]', seo_title = 'Codex 사용법 9편 - 샌드박스 보안, 외부 문맥 위협 및 감사 승인선' WHERE id = 1430;
UPDATE posts SET title = 'Codex 사용법 [10편: 엔터프라이즈 모노레포, 레거시 현대화 & 온보딩]', seo_title = 'Codex 사용법 10편 완결 - 역할별 온보딩, 모노레포 하네스 & 레거시 현대화' WHERE id = 1431;